name: flutterapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  flutter_staggered_grid_view: ^0.3.0
  flutter_bloc: ^4.0.0
  connectivity: ^0.4.8+6
  flutter_simple_dependency_injection: 1.0.2+1
  flutter_localizations:
    sdk: flutter
  mp_chart: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_driver:
    sdk: flutter
  test: 1.14.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Thin.otf
          style: normal
          weight: 100
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Ultralight.otf
          style: normal
          weight: 200
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Light.otf
          style: normal
          weight: 300
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Regular.otf
          style: normal
          weight: 400
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Medium.otf
          style: normal
          weight: 500
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Semibold.otf
          style: normal
          weight: 600
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Bold.otf
          style: normal
          weight: 700
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Heavy.otf
          style: normal
          weight: 800
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Black.otf
          style: normal
          weight: 900
    - family: SFUIText
      fonts:
        - asset: assets/fonts/SFUIText/SFUIText-Light.otf
          style: normal
          weight: 300
        - asset: assets/fonts/SFUIText/SFUIText-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/SFUIText/SFUIText-Regular.otf
          style: normal
          weight: 400
        - asset: assets/fonts/SFUIText/SFUIText-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/SFUIText/SFUIText-Medium.otf
          style: normal
          weight: 500
        - asset: assets/fonts/SFUIText/SFUIText-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/SFUIText/SFUIText-Semibold.otf
          style: normal
          weight: 600
        - asset: assets/fonts/SFUIText/SFUIText-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/SFUIText/SFUIText-Bold.otf
          style: normal
          weight: 700
        - asset: assets/fonts/SFUIText/SFUIText-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/SFUIText/SFUIText-Heavy.otf
          style: normal
          weight: 800
        - asset: assets/fonts/SFUIText/SFUIText-HeavyItalic.otf
          style: italic
          weight: 800

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
