import 'string_ids.dart';

const Map<String, String> ukrainian = {
  basketTitleId: "Кошик",
  locationTitleId: "Розташування",
  ordersTitleId: "Замовлення",
  profileTitleId: "Профіль",
  shopTitleId: "Магазин",
  stepsToFreeCoffeeId: "Кроків до безкоштовної кави",
  dailyId: "Щоденне",
  randomId: "Випадкове",
  bossId: "Начальник",
  achievementsId: "Досягнення",
  expId: "дос.",
  destroyedCroissantsId: "Знищувач круасанів",
  drankLattesId: "Випиті латте",
  drankAmericanosId: "Випиті американо",
  joinTheGameId: "Приєднатись до ігри",
  loyaltySystemId: "Система лояльності",
  giftCardsId: "Подарункові картки",
  bonusesId: "Бонуси",
  settingId: "Налаштування",
  paymentMethodsId: "Способи оплати",
  signOutId: "Вийти з аккаунта",
  loadingProfileFailedId: "Не вдалось завантажити профіль.",
  noInternetConnectionId: "Немає зв'язку",
  retryId: "Повторити спробу",
};