name: Danger

on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world! ${{ secrets.DANGER_GITHUB_API_TOKEN }} ---
      env:
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
    - name: Danger
      uses: danger/danger-js@9.1.8
      env:
        DANGER_DISABLE_TRANSPILATION: true
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}