name: Danger

on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Danger
      uses: danger/swift@3.0.0
      with:
          args: --failOnErrors --no-publish-check
      env:
        DANGER_DISABLE_TRANSPILATION: true
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}